// Name: ASS $S_2$
// Description: Adams Spectral Sequence for $S_2$. The $E_2$ page was generated by Amelia Perry's resolution program, the differentials and extensions were copied from Dan Isaksen.

"use strict";


let file_name = getJSONFilename("sseq");

Sseq.loadFromServer(file_name).catch((error) => console.log(error)).then((sseq) => {
    sseq._getXOffset = tools.fixed_tower_xOffset.bind(sseq);
    sseq._getYOffset = (c) => c.y_offset || 0;

    window.sseq = sseq;
    window.display = new BasicDisplay("#main");
//    display.setDifferentialColor(2, "cyan");
//    display.setDifferentialColor(3, "red");
//    display.setDifferentialColor(4, "green");
    display.on("draw", function() {
        let context = this.context;

        context.save();
        context.lineWidth = 1;
        context.strokeStyle = "#818181";
        context.moveTo(this.xScale(0), this.yScale(6/5));
        context.lineTo(this.xScale(50), this.yScale(10 + 6/5));
        context.stroke();
        context.restore();
    });

    display.setSseq(sseq);
    return;

}).catch(e => console.log(e));
